### ISSUE TITLE
SVGRoot.getShape() provides incorrect represantation

### ISSUE THREAD

**Issue by DanielKenREK** [blackears/svgSalamander#102]
The svg file "Verteilerdose.svg" is shown twice in the attached screenshot.

One icon is created via `SVGDiagram.render(g)`:
`URI uri = SVGCache.getSVGUniverse().loadSVG(new ByteArrayInputStream(typ.getSymbol()), typ.getBezeichnung());
SVGDiagram svgDiagram = SVGCache.getSVGUniverse().getDiagram(uri);
AffineTransform oldTransform = g.getTransform();
Color defaultColor = g.getColor();
g.translate(x-5, y);
g.transform(AffineTransform.getScaleInstance(10/svgDiagram.getWidth(), 10/svgDiagram.getWidth()));
svgDiagram.render(g);`

The other icon is created via `SVGRoot.getShape()`:
`URI uri = SVGCache.getSVGUniverse().loadSVG(new ByteArrayInputStream(typ.getSymbol()), typ.getBezeichnung());
SVGDiagram svgDiagram = SVGCache.getSVGUniverse().getDiagram(uri);
Shape shape = svgDiagram.getRoot().getShape();
Path2D legendeEintrag = new Path2D.Float(shape);
legendeEintrag.transform(AffineTransform.getScaleInstance(10/svgDiagram.getWidth(), 10/svgDiagram.getWidth()));
legendeEintrag.transform(AffineTransform.getTranslateInstance(x, y-10));
path.append(legendeEintrag, false);`

The represantation of the icon which is created via `SVGRoot.getShape()` is wrong as you can see in the attached Screenshot (see red bordered icon).

Is there a possibilty to get the correct represenation via `SVGRoot.getShape()`?

By the way: The respresnation of the icon "Steckdose.svg" is correct in both cases!

Is the cause of the problem the SVG file? In my opinion, the presentation should always be the same in both cases.

![screenshot](https://user-images.githubusercontent.com/75311983/225311556-e36218df-7314-4d42-9f33-3a1d41cd30ab.JPG)

![Verteilerdose](https://user-images.githubusercontent.com/75311983/225312317-a7c41394-408f-4d74-9829-49f4cddf6269.svg)

![Steckdose](https://user-images.githubusercontent.com/75311983/225311883-225f1ad1-2952-41ce-bfd2-e7182da87a62.svg)

**Comment by blackears** [comment]
The getShape() method here is being used mostly internally for clip testing.  It's transform might be something other than what you're expecting.  It is created by recursively merging together the entire tree of shapes.  You should use doPick() if you're trying to pick against the shape or render() if you're trying to draw it.

If you can provide a short program which demonstrates the problem, I can take a deeper look at it.

**Comment by blackears** [comment]
The svg files you attached have had their names mangled by Github, so I;m not sure which is Steckdose and which is Verteilerdose.  Also, the bottom most svg symbol shows as a black box if I view it as a standalone image in Firefox, so thre is a possibility the svg is malformed.

I also haven't really used Java in years and I also find Maven really confusing.    I'll give this a shot, but I might not be able to come up with a solution for this problem.

**Comment by weisJ** [comment]
In the second svg there is a rect with id `rect1667`, which has no fill or stroke. Yet it still will contribute to the roots shape resulting in the additional square being painted. The other lines aren't painted because they are ... well lines. The do not contribute to the shape as such.

Though I was wondering why you are painting the shape instead of the svg?

**Comment by blackears** [comment]
I've updated the code in Group to use another way to calculate the combined shape and am getting these result now.  On another note, @weisJ has a good point that you should be using the render() method to draw the svg rather than painting the shape yourself.

![image](https://user-images.githubusercontent.com/6724608/226213041-32637065-a069-49ac-99a8-c7da89e00189.png)

**Comment by blackears** [comment]
I don't think so.  It would still be a valid shape even without a fill and stroke.  Like an invisible hot spot.

**Comment by blackears** [comment]
I'm closing this now.  Please reopen if you're still having problems.

**Comment by DanielKenREK** [comment]
I want to reopen this issue because the problem still exists.

This is a very simple svg icon:

`<svg width="55mm" height="55mm" viewBox="0 0 55 55">
<path d="m28 3.5c-13-0.063-24 11-24 24-0.0032 13 11 24 24 24 13 0.023 24-11 24-24 1.2-15-12-24-24-24zm0.049 
	3c5.2 0.025 9.2 1.6 13 4.5 4.7 3.7 8.5 9.4 8.5 16-0.037 12-9.6 22-21 22-12-0.021-21-10-21-22 0.073-12 9.8-21 21-21z"/>
<path fill="black" stroke="black" stroke-width="3" d="m10 42 35-27" />
<path fill="black" stroke="black" stroke-width="3" d="m10 15 35 27" />
</svg>`

If the icon is rendered on a Graphics2D object everything looks fine. If I call getShape() the to lines are not drawn.

Here is a short test programm. Please fill in the right file location.

`import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.geom.AffineTransform;
import java.awt.geom.Path2D;
import java.io.File;

import javax.swing.JFrame;
import javax.swing.JPanel;

import com.kitfox.svg.SVGCache;
import com.kitfox.svg.SVGDiagram;
import com.kitfox.svg.SVGException;

public class Test {

	public static void main(String[] args) throws Exception {
		
		File svgFile = new File("...");
		SVGDiagram diagram = SVGCache.getSVGUniverse().getDiagram(svgFile.toURI());

		JPanel panel = new JPanel( new FlowLayout() ) {
			@Override
			public void paintComponent(Graphics g) {
				super.paintComponent(g);
				
				try {
					Graphics2D g2d = (Graphics2D) g;
					AffineTransform oldTransform = g2d.getTransform();
					g2d.setColor(Color.BLACK);
					
					double factor = Math.min(20/diagram.getWidth(),  20/diagram.getHeight());
					
					// Paint SVG icon "Verteilerdose" via render()  -> OK
					g2d.setColor(Color.BLACK);
					g2d.translate(80, 40);
					g2d.transform(AffineTransform.getScaleInstance(factor, factor));
					diagram.render(g2d);
					g2d.setTransform(oldTransform);
					

					// Paint SVG icon "Verteilerdose" via shape  -> not OK !!!!		
					Shape shape = diagram.getRoot().getShape();
					Path2D path = new Path2D.Float(shape);
					g2d.translate(110, 40);
					path.transform(AffineTransform.getScaleInstance(factor, factor));
					g2d.draw(path);
					g2d.setTransform(oldTransform);
					
					
				} catch (SVGException e) {
					e.printStackTrace();
				}
			}
		};

		JFrame frame = new JFrame( "SVG Test" );
		frame.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
		frame.getContentPane().add( panel );
		frame.setSize( 400, 200 );
		frame.setLocationRelativeTo( null );
		frame.setVisible( true );
	}
}`

**Comment by blackears** [comment]
I've not had a chance to run the program, but the getShape method isn't meant to work on lines since they enclose no area.
